version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    command: python manage.py test
    env_file:
      - .env
    depends_on:
      - db

  db:
    platform: linux/arm64/v8
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
