# Generated by Django 4.1.7 on 2023-03-23 16:17

from django.db import migrations
from django.db import migrations
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "Cinema_api_data.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_load_fixtures)
    ]
